#!/bin/sh

mpd &
sxhkd &
setbg &
trackpoint &
remaps &
xcompmgr &
xrdb -merge $HOME/.Xresources

# For Java windows (Matlab)
wmname LG3D

# bspc rule -a lxqt-desktop border=off manage=off

bspc rule -a zoom state=floating center=on follow=on border=off
# bspc rule -a "Whisker Menu" state=floating center=on follow=on border=off


# nl='
# '
# info=$(xrandr --listactivemonitors)
# IFS="$nl"
# set -- $info
# unset IFS
# for line do
#     case "$line" in
# 	'') ;;
# 	'Monitors:'*) num=${line##"${line%%?}"} ;;
# 	*[0-9]*) monitors="$monitors${nl}${line##*[[:space:]]}" ;;
#     esac
# done

# monitors=${monitors#*$nl}

monitors=$(xrandr --listactivemonitors | tail -n +2 | cut -d ' ' -f 6)
num=$(printf '%s\n' $monitors | wc -l)

case "$num" in
    1) bspc monitor $monitors -d 1 2 3 4 5 6 7 8 9 0 ;;
    2)
        primary="$(xrandr --listactivemonitors | grep '*' | cut -d ' ' -f 6)"
        secondary="$(printf $monitors | grep -v $primary)"
        bspc monitor $primary -d 1 2 3 4 5
        bspc monitor $secondary -d 6 7 8 9 0
        bspc wm --reorder-monitors "$primary" "$secondary"
        ;;
esac

bspc config border_width         2
bspc config window_gap           2

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding		 30

bspc config normal_border_color  \#181818
bspc config focused_border_color \#00BFFF
# bspc config urgent_border_color  \#000000
# bspc config presel_border_color  \#000000
bspc config pointer_modifier mod4

# Remove unplugged monitors
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config automatic_scheme longest_side
bspc config initial_polarity second_child

# Set monocle by default
for n in $(seq 1 10); do
    bspc desktop $n --layout monocle
done
